
data:extend(
{
  {
    type = "fluid",
    name = "quadricyclane",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0, b=0},
    flow_color = {r=1, g=0, b=0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/quadricyclane.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "norbornadiene",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=1, b=0},
    flow_color = {r=1, g=1, b=0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/norbornadiene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "acetylene",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0.9, b=0.9},
    flow_color = {r=0.9, g=0.9, b=0.9},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/acetylene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "argon",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0.4, b=1},
    flow_color = {r=0.3, g=0.1, b=8},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/argon.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "z1"
  },
  {
    type = "fluid",
    name = "xenon",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.78, g=0.95, b=0.96},
    flow_color = {r=0.61, g=0.97, b=1.0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/xenon.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "z2"
  },
  {
    type = "fluid",
    name = "lox",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1.0, g=1.0, b=1.0},
    flow_color = {r=1.0, g=1.0, b=1.0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/lox.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "z3"
  },
  {
    type = "fluid",
    name = "cyclopentadiene",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0.9, b=0.7},
    flow_color = {r=0.9, g=0.9, b=0.7},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/cyclopentadiene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "dark-matter",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0, b=0},
    flow_color = {r=0, g=0, b=0},
    max_temperature = 30,
    icon = "__Darkstar_utilities__/graphics/icons/cyclopentadiene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "aizhan-matter",
    default_temperature = 0,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0.4, b=1},
    flow_color = {r=0, g=0.8, b=1},
    max_temperature = 0,
    icon = "__Darkstar_utilities__/graphics/icons/aizhan-matter.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "antithetical-matter",
    default_temperature = -5000,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0, b=0.1},
    flow_color = {r=0, g=0, b=0.1},
    max_temperature = 5000,
    icon = "__Darkstar_utilities__/graphics/icons/antithetical-matter.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "quantum-waste",
    default_temperature = 31415,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=1, b=0},
    flow_color = {r=1, g=1, b=0},
    max_temperature = 31415,
    icon = "__Darkstar_utilities__/graphics/icons/quantum-waste.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "blood",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.3, g=0, b=0},
    flow_color = {r=0.3, g=0, b=0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/quadricyclane.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "copper-sulfate",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0.2, b=1},
    flow_color = {r=0.3, g=0.2, b=1},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/copper-sulfate.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
})

